### ISSUE TITLE
Touch device awareness

### ISSUE THREAD

**Issue by swesley** [isabolic/apex-plg-datetimepicker#1]
Hi, nice tidy plugin, but when trying it out on a touch device (iPad) I have a few suggestions.

Tapping away from calendar does not dismiss the calendar, it took me a while to work out I had to close the keyboard. I'm not sure if this is device specific.

I also disable text entry for touch screens so suppress the virtual keyboard when the picker opens. Do you think this could be applied within the plugin?

**Comment by isabolic** [comment]
Hi @swesley 

thank you for your feedback.  I will look into it.

Best Regards
isabolic

**Comment by isabolic** [comment]
Hi @swesley,

 I have setup better support for touch devices  #b52f617, it's now available on [https://apex.oracle.com/pls/apex/f?p=101959:8](https://apex.oracle.com/pls/apex/f?p=101959:8)

also I have added a close (check icon) and clear (times icon) button for picker only on touch devices.

**Comment by isabolic** [comment]
This is not yet packed in release.
